/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms.pro;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.awt.Image; 
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.lang.System.*;
import javax.swing.JFrame;
import javax.swing.ImageIcon;

/**
 *
 * @author lt1
 */
public class Bookings extends javax.swing.JFrame {

    JpanelLoader jpload = new JpanelLoader();
    /**
     * Creates new form Bookings
     */
    public Bookings() {
        initComponents();
        
        MainDesk dekts = new MainDesk();
        jpload.jPanelLoader(jpnlPayDis, dekts);
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btnFrontDesk = new javax.swing.JButton();
        jpnlPayDis = new javax.swing.JPanel();
        btnSalesReports = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 0), new java.awt.Dimension(1000, 32767));
        jLabel2 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        btnChgShow = new javax.swing.JButton();
        btnPayShow = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hostel Management System");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/hms/pro/img/Logo.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFrontDesk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/img/customer.png"))); // NOI18N
        btnFrontDesk.setText("FRONT DESK");
        btnFrontDesk.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFrontDesk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrontDeskActionPerformed(evt);
            }
        });
        getContentPane().add(btnFrontDesk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, 60));

        jpnlPayDis.setMinimumSize(new java.awt.Dimension(860, 0));

        javax.swing.GroupLayout jpnlPayDisLayout = new javax.swing.GroupLayout(jpnlPayDis);
        jpnlPayDis.setLayout(jpnlPayDisLayout);
        jpnlPayDisLayout.setHorizontalGroup(
            jpnlPayDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1340, Short.MAX_VALUE)
        );
        jpnlPayDisLayout.setVerticalGroup(
            jpnlPayDisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );

        getContentPane().add(jpnlPayDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 1340, 793));

        btnSalesReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/img/reports.png"))); // NOI18N
        btnSalesReports.setText("REPORTS");
        btnSalesReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalesReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesReportsActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalesReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, 60));
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 799, 1277, -1));

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/img/Logo.png"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 124, 100));

        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/img/supplier.png"))); // NOI18N
        btnAdmin.setText(" ADMIN");
        btnAdmin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, 60));

        btnChgShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/img/invo.png"))); // NOI18N
        btnChgShow.setText("CHARGES");
        btnChgShow.setHideActionText(true);
        btnChgShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnChgShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChgShowActionPerformed(evt);
            }
        });
        getContentPane().add(btnChgShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, 60));

        btnPayShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/img/invo.png"))); // NOI18N
        btnPayShow.setText("PAYMENT");
        btnPayShow.setHideActionText(true);
        btnPayShow.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPayShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayShowActionPerformed(evt);
            }
        });
        getContentPane().add(btnPayShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 140, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFrontDeskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrontDeskActionPerformed
        // TODO add your handling code here:
       
        MainDesk dekts = new MainDesk();
        jpload.jPanelLoader(jpnlPayDis, dekts);
    }//GEN-LAST:event_btnFrontDeskActionPerformed

    private void btnPayShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayShowActionPerformed
        // TODO add your handling code here:
        Payments sp = new Payments();
        jpload.jPanelLoader(jpnlPayDis, sp);
        
    }//GEN-LAST:event_btnPayShowActionPerformed

    private void btnSalesReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesReportsActionPerformed
        // TODO add your handling code here:
         ReportsMain rpmnu = new ReportsMain();
        jpload.jPanelLoader(jpnlPayDis, rpmnu);
    }//GEN-LAST:event_btnSalesReportsActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        AdminMenu admns = new AdminMenu();
        jpload.jPanelLoader(jpnlPayDis, admns);
        
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnChgShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChgShowActionPerformed
        Charges chrg = new Charges();
        jpload.jPanelLoader(jpnlPayDis, chrg);
    }//GEN-LAST:event_btnChgShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bookings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bookings().setVisible(true);
            }
        });
    }
    
    
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnChgShow;
    private javax.swing.JButton btnFrontDesk;
    private javax.swing.JButton btnPayShow;
    private javax.swing.JButton btnSalesReports;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jpnlPayDis;
    // End of variables declaration//GEN-END:variables
}
